kafka:
  bootstrap_servers:
    - "rpk0.bitquery.io:9093"
    - "rpk1.bitquery.io:9093"
    - "rpk2.bitquery.io:9093"
  group_id: "solanatestS-group-97"
  topic: "solana.balance_updates"
  security:
    protocol: "SASL_SSL"
    sasl_mechanisms: "SCRAM-SHA-512"
    username: "solanatestS"
    password: "Qx4Zs4s7ZpWtYd6WBk0Ms8jay1ROx3"
    ssl_ca_location: "env/server.cer.pem"
    ssl_key_location: "env/client.key.pem"
    ssl_certificate_location: "env/client.cer.pem"
    endpoint_identification_algorithm: "none"
  auto_offset_reset: "latest"
  poll_interval_ms: 250

application:
  webhook_url: "https://v5gegme2a6.execute-api.eu-north-1.amazonaws.com/default/transactionWebhookV2"
  transfer_webhook_url: "https://v5gegme2a6.execute-api.eu-north-1.amazonaws.com/default/transferWebhook"
  wallet_list_url: "https://v5gegme2a6.execute-api.eu-north-1.amazonaws.com/default/getWalletList"
  database_endpoint: "http://13.49.221.13:8000/api/submit"
  wallet_update_interval: 30
  uid_charset: "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
  sol_to_usd_api_url: "https://api.coingecko.com/api/v3/simple/price?ids=solana&vs_currencies=usd"
  save_matches: "on"

interpreter:
  bitquery_token: "ory_at_-mbOudJvKgJ1bSQ9upzINUpt1FHMbXHYd1Sa5yKs_ZU.DiWP8GQ7ZgbhrE1-Xdv0ibf32OfWJefg15cU0Y-mqMY"
  python: "venv/bin/python"
  swap_detector_script: "scripts/test.py"

metrics:
  flush_interval_seconds: 60
  cloud_endpoint: "https://v5gegme2a6.execute-api.eu-north-1.amazonaws.com/default/go-kafka-sol-listener-metrics"
  max_metrics_cache_size: 10000

